version: '3.8'

services:
  barcode-server:
    # build: .
    image: markusressel/barcode-server:latest
    environment:
      - PUID=0
      - PGID=0
    devices:
      - "/dev/input"
    volumes:
      # mount a YAML configuration file into /app/barcode_server.yaml:
      - "./barcode_server.yaml:/app/barcode_server.yaml"
    networks:
      - docker-elk
    ports:
      - "8000:8000"
    restart: on-failure
networks:
  docker-elk:
    driver: bridge