name: Docker Image Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # this writes the tag name into GIT_TAG_NAME
      - name: Get tag name
        uses: little-core-labs/get-git-tag@v3.0.1
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag markusressel/barcode-server:$GIT_TAG_NAME
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push the Docker image
        run: docker push markusressel/barcode-server:$GIT_TAG_NAME
